name: 'NeVips'
main: net.nostalase.vips.Main
version: '1.0'
depend: ['CraftingStore', 'NostalaseCore']

commands:
  vip:
      permission: nevips.manage
      permission-message: §c§l Você não pode executar esse comando.
      aliases: [nevip]
  superpickae:
      permission: nevips.vip.superpick
      permission-message: §c§l Você não pode executar esse comando.
      aliases: [superpick]

permissions:
  nevips.manage:
    default: op
  nevips.vip.chunks:
    default: op
  nevips.vip.superpick:
    default: op
  nevips.vip.slot:
    default: op
