name: 'NeVips'
main: net.nostalase.vips.Main
version: '1.0'
depend: ['CraftingStore']

commands:
  vip:
      permission: nevips.manage
      permission-message: §c§l Você não pode executar esse comando.
      aliases: [nevip]

permissions:
  nevips.manage:
    default: op